# authentication error messages
authentication.err.validation.authenticator.notfound=Kan ikke godkjenne, finner ikke godkjenner med navnet {0}
authentication.err.validation.authenticator.notactive=Godkjenneren er ikke aktiv

authentication.err.authentication=Kan ikke godkjenne, brukernavnet eller passordet er feil. Brukernavn: {0} \u00c5rsak {1}
authentication.err.connection=Kan ikke koble til {0}. \u00c5rsak {1}
authentication.err.communication=Kan ikke kommunisere med {0}. \u00c5rsak {1}

# LDAP error messages
authentication.err.connection.ldap.authenticator.unknownhost=Kan ikke koble til, LDAP-verten {0} er ukjent
authentication.err.connection.ldap.user.notfound=Finner ikke LDAP-brukeren {0}
authentication.err.connection.ldap.manager.notfound=Finner ikke LDAP-administratorbrukeren {0}
authentication.err.connection.ldap.search=Kan ikke s\u00f8ke i LDAP. \u00c5rsak {0}

# PASSTHRU
authentication.err.connection.passthru.server=Kan ikke \u00e5pne \u00f8kt til gjennomgangsserver
authentication.err.passthru.token.unsupported=Tokentype for godkjenning st\u00f8ttes ikke
authentication.err.passthru.guest.notenabled=Gjestep\u00e5logginger er deaktivert
authentication.err.passthru.user.disabled=Konto er deaktivert
authentication.err.passthru.user.notfound=Finner ikke gjennomgangsbrukeren {0}

# Authentication Diagnostic Steps
authentication.step.ldap.validation=Validering av foresp\u00f8rsel
authentication.step.ldap.connecting=Koble til LDAP-server {0} 
authentication.step.ldap.connected=Koblet til LDAP-server {0} med hovedkonto: {1}
authentication.step.ldap.lookup=Sl\u00e5 opp testbrukeren bruker-ID:{0} med sp\u00f8rringen: {1}
authentication.step.ldap.lookedup=Slo opp testbrukeren userID:{0}, fant unikt navn (DN):{1}
authentication.step.ldap.format.user=Brukernavnformat spesifisert, userNameFormat:{2} Formater brukeren userID:{0} for \u00e5 lage unikt navn (DN):{1}
authentication.step.ldap.authentication=Verifiser userID:{0}


# Sync Summary message 
synchronization.summary.status={0} bruker(e) og {1} gruppe(r) behandlet


# Error messages
authentication.ldap.validation.authenticator.notfound=Finner ikke godkjenner

# Synchronization Diagnostic Steps
synchronization.step.users=Fant {0} brukere
synchronization.step.groups=Fant {0} grupper
synchronization.step.users.lastsynced=Brukere siste vellykkede synkronisering {0}
synchronization.step.groups.lastsynced=Grupper siste vellykkede synkronisering {0}

synchronization.err.ldap.search=Feil under LDAP-s\u00f8k. \u00c5rsak:{0}
synchronization.err.ldap.get.user.id.missing=Bruker mangler bruker-ID-attributt DN = {0}, attributeName = {1})
synchronization.err.ldap.get.group.id.missing=Gruppe mangler bruker-ID-attributt DN = {0}, attributeName = {1})

synchronization.err.ldap.search.base.invalid=Ugyldig s\u00f8kebase {0} \u00e5rsak: {1}

synchronization.err.ldap.group.member.missing.exception=''Klarte ikke \u00e5 l\u00f8se medlem av gruppe {0} med unikt navn: {1} \u00e5rsak {2});
synchronization.err.ldap.group.member.missing=''Klarte ikke \u00e5 l\u00f8se medlem av gruppe {0} med unikt navn: {1});



       



